services:
  postgres_db: 
    container_name: postgres_container
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW_USER: ${AIRFLOW_USER}
      AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD}
      AIRFLOW_DB: ${AIRFLOW_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts/init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    networks:
      - meteo_network

  airflow:
    container_name: airflow_container
    build: .
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PASSWORD}@postgres_db:5432/${AIRFLOW_DB}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
    depends_on:
      - postgres_db
    networks:
      - meteo_network
    command: bash -c "airflow db migrate && airflow standalone"

volumes:
  postgres_data:

networks:
  meteo_network:
    driver: bridge
    