services:
  postgres_db: 
    container_name: postgres_container
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW_DB_USER: ${AIRFLOW_DB_USER}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      AIRFLOW_DB_NAME: ${AIRFLOW_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts/init_dbs.sh:/docker-entrypoint-initdb.d/init_dbs.sh
    networks:
      - meteo_network

  airflow:
    container_name: airflow_container
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@postgres_db:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__AUTH_MANAGER: 'airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager'
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./.env:/opt/airflow/.env
    depends_on:
      - postgres_db
    networks:
      - meteo_network
    command: >
      bash -c "airflow db migrate && 
      (airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME} --password ${_AIRFLOW_WWW_USER_PASSWORD} --firstname Kiet --lastname Admin --role Admin --email giakiet.work@gmail.com || true) ; 
      airflow scheduler & 
      airflow triggerer & 
      airflow dag-processor & 
      airflow api-server"

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    working_dir: /usr/app
    # Ghi đè ENTRYPOINT mặc định của dbt image để giữ container luôn sống ngầm.
    # Nhờ vậy chúng ta có thể chui vào container và gõ lệnh "dbt run", "dbt test" nhiều lần.
    entrypoint: ["tail", "-f", "/dev/null"]
    env_file:
      - .env
    environment:
      # Ghi đè lại host DB vì trong mạng nội bộ docker, postgres có tên là 'postgres_db' chứ không phải 'localhost'
      POSTGRES_HOST: postgres_db 
      POSTGRES_PORT: 5432
    volumes:
      - ./dbt-transform:/usr/app
      - ./.dbt:/root/.dbt
    depends_on:
      - postgres_db
    networks:
      - meteo_network

volumes:
  postgres_data:

networks:
  meteo_network:
    driver: bridge
    