name: 'weather_meteo_transform'
version: '1.0.0'
config-version: 2

# Profile name phải khớp với tên khai báo trong file profiles.yml
profile: 'weather_meteo_transform'

# Thư mục chứa model dbt (các file .sql)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_meteo_transform:
    # Cấu hình Materialization theo Folder (Nguyên tắc OOP)
    staging:
      +materialized: view  # Tầng Staging chỉ tạo View ảo, nhẹ và nhanh
    silver:
      +materialized: table # Tầng Silver sẽ tạo Table vật lý (hoặc Incremental sau này)
